/* THE SEVERITY GLYPHS, LIFTED OUT OF BREACHPROBE'S OWN ICON TABLE.
 *
 *   node ops/build-glyphs.mjs
 *
 * House rule: every icon on every Kynth Studios product is Solar bold-duotone. BreachProbe already
 * vendors the bodies it uses into `src/components/Icon.tsx` (generated there by its own
 * ops/build-icons.mjs from @iconify-json/solar), so the popup takes the SAME path data rather than
 * drawing a second set. `Severity.tsx` is what maps a severity onto a glyph name, and that map is
 * copied here.
 *
 * Writes src/glyphs.js. Re-run it whenever BreachProbe's icon table changes.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const REPO = path.resolve(process.env.BREACHPROBE_REPO || path.join(ROOT, "..", "breachprobe"));
const ICON_TSX = path.join(REPO, "src/components/Icon.tsx");

/* src/components/Severity.tsx, SEV_ICON, plus the two the popup header and footer use. */
const WANT = {
  critical: "critical",
  high: "high",
  medium: "medium",
  low: "low",
  pass: "pass",
  scan: "scan",
  external: "external",
};

if (!existsSync(ICON_TSX)) {
  console.error(`cannot build glyphs: ${ICON_TSX} is not on this disk`);
  console.error("set BREACHPROBE_REPO to the checkout, or leave src/glyphs.js as it is");
  process.exit(1);
}

const src = readFileSync(ICON_TSX, "utf8");
const m = src.match(/export const ICON_BODIES = \{([\s\S]*?)\n\}(?: as const)?;/);
if (!m) {
  console.error("ICON_BODIES not found in Icon.tsx");
  process.exit(1);
}
const bodies = JSON.parse("{" + m[1].replace(/,\s*$/, "") + "}");

const out = {};
for (const [key, name] of Object.entries(WANT)) {
  if (!bodies[name]) {
    console.error(`Icon.tsx no longer carries "${name}"`);
    process.exit(1);
  }
  out[key] = bodies[name];
}

const file = path.join(ROOT, "src", "glyphs.js");
writeFileSync(
  file,
  `/* GENERATED by ops/build-glyphs.mjs from ${path.relative(REPO, ICON_TSX)} in ~/Projects/breachprobe.\n` +
    ` * Do not hand-edit. Solar (bold duotone) by 480 Design, CC BY 4.0.\n` +
    ` * The severity-to-glyph map is Severity.tsx's SEV_ICON. */\n\n` +
    `export const GLYPHS = ${JSON.stringify(out, null, 2)};\n\n` +
    `/** One Solar glyph as an inline SVG string, painting in currentColor. */\n` +
    `export function glyph(name, size = 14) {\n` +
    `  const body = GLYPHS[name];\n` +
    `  if (!body) return "";\n` +
    `  return \`<svg viewBox="0 0 24 24" width="\${size}" height="\${size}" aria-hidden="true" focusable="false">\${body}</svg>\`;\n` +
    `}\n`,
);
console.log(`wrote ${path.relative(ROOT, file)} with ${Object.keys(out).length} glyphs`);
